server:
  port: 9000

spring:
  application:
    name: "bitbunker-api"
  profiles:
    active: "dev"
  datasource:
    url: jdbc:mysql://localhost:3300/bitbunker-db
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
